// <auto-generated />
using System;
using Klir.TechChallenge.Web.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Klir.TechChallenge.Web.Api.Migrations
{
    [DbContext(typeof(AplicationDBContext))]
    [Migration("20210613225148_Adding_relation")]
    partial class Adding_relation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Klir.TechChallenge.Web.Api.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<int?>("PromotionsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PromotionsId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Klir.TechChallenge.Web.Api.Models.Promotions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Promotion")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("Klir.TechChallenge.Web.Api.Models.Products", b =>
                {
                    b.HasOne("Klir.TechChallenge.Web.Api.Models.Promotions", "Promotions")
                        .WithMany("Products")
                        .HasForeignKey("PromotionsId");

                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("Klir.TechChallenge.Web.Api.Models.Promotions", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
